export const REDUX_HOME_MAP_TYPE_OPTIONS = {
  PICKUP_LOCATION: "PICKUP_LOCATION",
  CHOOSE_VEHICLE_TYPE: "CHOOSE_VEHICLE_TYPE",
  CHOOSE_PERFECT_PILOT: "CHOOSE_PERFECT_PILOT",
  RATE_PILOT: "RATE_PILOT",
  FINDING_PILOT: "FINDING_PILOT",
  SERVICE_NOT_AVAILABLE: "SERVICE_NOT_AVAILABLE",
};

export const REDUX_HOME_MAP_VISIBLE_MARKER_TYPE_OPTIONS = {
  BOTH: "both",
  ORIGIN: "origin",
  DESTINATION: "destination",
};
